tracker_type: botsort
track_high_thresh: 0.60   
track_low_thresh: 0.09    
new_track_thresh: 0.65   
track_buffer: 100        
match_thresh: 0.85        
fuse_score: False         
gmc_method: sparseOptFlow 
proximity_thresh: 0.45    
appearance_thresh: 0.2   
with_reid: False         