tracker_type: botsort  
track_high_thresh: 0.5  
track_low_thresh: 0.1  
new_track_thresh: 0.6  
track_buffer: 180  
match_thresh: 0.8  
fuse_score: True  
gmc_method: None  
proximity_thresh: 0.5  
appearance_thresh: 0.2  
with_reid: False
