tracker_type: botsort
with_reid: False

track_high_thresh: 0.6
track_low_thresh: 0.15
new_track_thresh: 0.7
track_buffer: 120
match_thresh: 0.8
fuse_score: True
proximity_thresh: 0.5
appearance_thresh: 0.25

gmc_method: orb
