tracker_type: botsort
track_high_thresh: 0.4   
track_low_thresh: 0.15    
new_track_thresh: 0.5   
track_buffer: 90        
match_thresh: 0.8        
fuse_score: False         
gmc_method: sparseOptFlow 
proximity_thresh: 0.35    
appearance_thresh: 0.85   
with_reid: True
model: auto

